CREATE TABLE ERS_USER_ROLES(
	ERS_USER_ROLE_ID integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	USER_ROLE varchar(10) NOT NULL
);

CREATE TABLE ERS_USERS(
	ERS_USERS_ID integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ERS_USERNAME varchar(50) UNIQUE NOT NULL,
	ERS_PASSWORD varchar(50) NOT NULL, --DO NOT ACTUALLY STORE PLAINTEXT PASSWORD IN FINAL PRODUCT--
	USER_FIRST_NAME varchar(100) NOT NULL,
	USER_LAST_NAME varchar(100) NOT NULL,
	USER_EMAIL varchar(150) NOT NULL UNIQUE,
	USER_ROLE_ID integer NOT NULL REFERENCES ERS_USER_ROLES(ERS_USER_ROLE_ID)
);
	
CREATE TABLE ERS_REIMBURSEMENT_STATUS(
	REIMB_STATUS_ID integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	REIMB_STATUS varchar(10) NOT NULL
);

CREATE TABLE ERS_REIMBURSEMENT_TYPE(
	REIMB_TYPE_ID integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	REIMB_TYPE varchar(10) NOT NULL
);

CREATE TABLE ERS_REIMBURSEMENT(
	REIMB_ID integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	REIMB_AMOUNT integer NOT NULL,
	REIMB_SUBMITTED timestamp NOT NULL,
	REIMB_RESOLVED timestamp NOT NULL,
	REIMB_DESCRIPTION varchar(250),
	REIMB_RECEIPT bytea,
	REIMB_AUTHOR integer NOT NULL REFERENCES ERS_USERS(ERS_USERS_ID),
	REIMB_RESOLVER integer REFERENCES ERS_USERS(ERS_USERS_ID),
	REIMB_STATUS_ID integer NOT NULL REFERENCES ERS_REIMBURSEMENT_STATUS(REIMB_STATUS_ID),
	REIMB_TYPE_ID integer NOT NULL REFERENCES ERS_REIMBURSEMENT_TYPE(REIMB_TYPE_ID)
);